version: '3.7'
services:
  nextjs-dashboard-db:
    image: postgres:16.1-alpine3.19
    volumes:
      - dashboard-mandir-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5435:5432"
volumes:
  dashboard-mandir-data: